version: '3.8'

services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
      - SERVICE_FQDN_FRONTEND_80
      - VITE_SERVICE_URL_BACKEND=${SERVICE_URL_BACKEND}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVICE_FQDN_BACKEND_3001
    env_file:
      - .env
    restart: unless-stopped
